//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\XcDesignCam\XcDesignCam\Application\Standard.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Administrator
//              Version: NX 7.5
//              Date: 08-11-2018  (Format: mm-dd-yyyy)
//              Time: 10:07
//
//==============================================================================

#ifndef STANDARD_H_INCLUDED
#define STANDARD_H_INCLUDED

#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_ListBox.hxx>
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class Standard;
extern Standard *theStandard;

class Standard
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    Standard();
    ~Standard();
    int Show();
    
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int cancel_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    int filter_cb(NXOpen::BlockStyler::UIBlock*  block, NXOpen::TaggedObject* selectObject);
    
private:
    std::string theDialogName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::UIBlock* scrolledStdWindow;// Block type: Scrolled Window
    NXOpen::BlockStyler::UIBlock* enumCatalog;// Block type: Enumeration
    NXOpen::BlockStyler::ListBox* listbox1;// Block type: List Box
    NXOpen::BlockStyler::ListBox* listbox2;// Block type: List Box
    NXOpen::BlockStyler::UIBlock* stringSearch;// Block type: String
    NXOpen::BlockStyler::UIBlock* tabControl;// Block type: Tabs Page
    NXOpen::BlockStyler::UIBlock* tabPage1;// Block type: Group
    NXOpen::BlockStyler::UIBlock* labelBimap1;// Block type: Label
    NXOpen::BlockStyler::UIBlock* stringBomSize;// Block type: String
    NXOpen::BlockStyler::UIBlock* tabPage;// Block type: Group
    NXOpen::BlockStyler::UIBlock* labelBimap2;// Block type: Label
    NXOpen::BlockStyler::UIBlock* tabPage2;// Block type: Group
    NXOpen::BlockStyler::UIBlock* labelBimap3;// Block type: Label
    NXOpen::BlockStyler::UIBlock* scrolledWindow;// Block type: Scrolled Window
    NXOpen::BlockStyler::UIBlock* enumParent;// Block type: Enumeration
    NXOpen::BlockStyler::UIBlock* enumRepsition;// Block type: Enumeration
    NXOpen::BlockStyler::UIBlock* enumRefset;// Block type: Enumeration
    NXOpen::BlockStyler::UIBlock* button0;// Block type: Button
    NXOpen::BlockStyler::UIBlock* button01;// Block type: Button
    NXOpen::BlockStyler::UIBlock* button02;// Block type: Button
    NXOpen::BlockStyler::UIBlock* button03;// Block type: Button
    NXOpen::BlockStyler::UIBlock* button04;// Block type: Button
    NXOpen::BlockStyler::UIBlock* button05;// Block type: Button
    NXOpen::BlockStyler::UIBlock* buttonAssemToSolid;// Block type: Button
    NXOpen::BlockStyler::UIBlock* toggle0;// Block type: Toggle
    NXOpen::BlockStyler::UIBlock* enum04;// Block type: Enumeration
    
};
#endif //STANDARD_H_INCLUDED
